/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddContactForm: typeof import('./src/components/AddContactForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazPhoneNumberInput: typeof import('maz-ui/components/MazPhoneNumberInput')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
